<script>
	import Slider from '../components/Slider.svelte';
</script>

<svelte:head>
	<title>I&apos;m a cute little tab</title>
	<meta name="description" content="Generated by create next app" />
	<link rel="icon" href="/favicon.png" />
</svelte:head>

<main>
	<div class="m-4 w-auto shadow rounded-[6px]">
		<div
			class="flex flex-row-reverse items-center p-16 rounded-t-[6px] h-[45vh] bg-gradient-to-r from-cyan-500 to-blue-500">
			<p class="font-black text-white text-8xl">
				Well, <br />
				hello there.
			</p>
		</div>
		<div class="flex flex-row">
			<div class="h-auto w-[70vw]">
				<img src="janse.jpg" alt="My beautiful beautiful face" />
			</div>
			<div class="flex flex-col p-10 justify-center divide-y-4">
				<h1 class="text-6xl pb-2">Hey, I&apos;m Janse</h1>
				<p class="text-xl pt-1">
					Lorem ipsum blablabla soon there will be some nice text here. If you&apos;re a good UI
					designer and your eyes are bleeding right now I&apos;m deeply sorry.
				</p>
			</div>
		</div>
		<div class="flex flex-row items-center bg-gray-700 h-36 justify-center">
			<Slider />
		</div>
		<div class="flex flex-row items-center p-16 rounded-b-[6px] h-[45vh] bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
			<p class="w-[60vw] font-black text-white text-8xl">
				Stay <br />
				in touch.
			</p>
			<p class="text-white font-bold text-4xl">Write me at <b><u><a href="mailto:hey@janse.xyz" title="Send a mail to me" target="_blank">hey@janse.xyz</a></u></b></p>
		</div>
	</div>
</main>
